-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-06 10:48:50 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Componenta 
    ( 
     ID_buchet NUMBER (4)  NOT NULL , 
     Culoare   VARCHAR2 (20)  NOT NULL , 
     Nume      VARCHAR2 (20)  NOT NULL , 
     Cantitate NUMBER (3)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Componenta 
    ADD CONSTRAINT componenta_cantitate_ck 
    CHECK (cantitate > 0) 
;

ALTER TABLE Componenta 
    ADD CONSTRAINT Componenta_PK PRIMARY KEY ( ID_buchet, Culoare, Nume ) ;

-- LARISA
-- colectie de record-uri
-- pentru a trimite mai multe flori ca parametru la procedura
CREATE OR REPLACE PACKAGE pachet_buchete AS
    TYPE t_componenta_rec IS RECORD (
        nume componenta.nume%TYPE,
        culoare componenta.culoare%TYPE,
        cantitate componenta.cantitate%TYPE
    );

    TYPE t_lista_componente IS TABLE OF t_componenta_rec INDEX BY PLS_INTEGER;
END pachet_buchete;
/

CREATE TABLE Produs 
    ( 
     ID_furnizor NUMBER (10)  NOT NULL , 
     Nume        VARCHAR2 (20)  NOT NULL , 
     Culoare     VARCHAR2 (20)  NOT NULL , 
     Pret        NUMBER (5,2) , 
     Cantitate   NUMBER (3) 
    ) 
    LOGGING 
;

ALTER TABLE Produs 
    ADD CONSTRAINT produs_pret_ck 
    CHECK (pret > 0) 
;

ALTER TABLE Produs 
    ADD CONSTRAINT produs_cantitate_ck 
    CHECK (cantitate >= 0) 
;

ALTER TABLE Produs 
    ADD CONSTRAINT Produs_PK PRIMARY KEY ( ID_furnizor, Culoare, Nume ) ;

-- SIMONA
create or replace package pachet_produse as
    type prod_record_type is record(
        nume produs.nume%type,
        culoare produs.culoare%type,
        cantitate produs.cantitate%type);
    type prod_table_type is table of prod_record_type INDEX BY PLS_INTEGER;
    
end pachet_produse;
/

CREATE TABLE Floare 
    ( 
     Nume    VARCHAR2 (20)  NOT NULL , 
     Culoare VARCHAR2 (20)  NOT NULL , 
     Pret    NUMBER (5,2)  NOT NULL , 
     Stoc    NUMBER (3)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Floare 
    ADD CONSTRAINT floare_pret_ck 
    CHECK (pret > 0) 
;

ALTER TABLE Floare 
    ADD CONSTRAINT floare_stoc_ck 
    CHECK (stoc >= 0) 
;

ALTER TABLE Floare 
    ADD CONSTRAINT Floare_PK PRIMARY KEY ( Culoare, Nume ) ;

ALTER TABLE Floare 
    ADD CONSTRAINT Floare__UN UNIQUE ( Nume , Culoare ) ;

CREATE TABLE Buchet 
    ( 
     ID_buchet NUMBER (4)  NOT NULL , 
     Ambalaj   NUMBER (1)  NOT NULL , 
     Pret      NUMBER (6,2)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Buchet 
    ADD CONSTRAINT buchet_pret_ck 
    CHECK (pret > 0) 
;

ALTER TABLE Buchet 
    ADD CONSTRAINT Buchet_PK PRIMARY KEY ( ID_buchet ) ;

-- LARISA
CREATE OR REPLACE FUNCTION calculeaza_pret_buchet
(
    p_componente IN pachet_buchete.t_lista_componente,
    p_ambalaj IN buchet.ambalaj%TYPE
)
RETURN NUMBER
AS
    v_pret_floare floare.pret%TYPE;
    v_pret_total buchet.pret%TYPE := 0;
BEGIN
    IF p_componente.COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20031,
            'Buchetul trebuie sa aiba cel putin o componenta.'
        );
    END IF;

    FOR i in 1 .. p_componente.COUNT LOOP
        SELECT pret
        INTO v_pret_floare
        FROM floare
        WHERE nume = p_componente(i).nume AND
            culoare = p_componente(i).culoare;

        v_pret_total := v_pret_total + v_pret_floare * p_componente(i).cantitate;
    END LOOP;

    IF p_ambalaj = 1 THEN
        v_pret_total := v_pret_total + 30;
    END IF;

    RETURN v_pret_total;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(
            -20032,
            'Nu exista una sau mai multe flori pentru acest buchet.'
        );
END calculeaza_pret_buchet;
/

-- SIMONA
create or replace function get_pret_produs(
    f_id_furnizor produs.id_furnizor%type,
    f_nume produs.nume%type,
    f_culoare produs.culoare%type)
return produs.pret%type 
as
    v_pret produs.pret%type;
begin

    select pret into v_pret
    from produs
    where id_furnizor = f_id_furnizor and
        lower(nume) = lower(f_nume) and 
        lower(culoare) = lower(f_culoare);
        
    return v_pret;
    
exception
    when NO_DATA_FOUND then 
        return 0;
end;
/

-- LARISA
CREATE OR REPLACE FUNCTION get_stoc_floare
(
    p_nume IN floare.nume%TYPE,
    p_culoare IN floare.culoare%TYPE
)
RETURN NUMBER
AS
    v_stoc floare.stoc%TYPE;
BEGIN
    SELECT stoc
    INTO v_stoc
    FROM floare
    WHERE LOWER(nume)=LOWER(p_nume) AND
        LOWER(Culoare)=LOWER(p_culoare);

    RETURN v_stoc;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END get_stoc_floare;
/

-- SIMONA
create or replace function get_stoc_produs(
    f_id_furnizor produs.id_furnizor%type,
    f_nume produs.nume%type,
    f_culoare produs.culoare%type)
return produs.cantitate%type 
as
    v_stoc produs.cantitate%type;
begin

    select cantitate into v_stoc
    from produs
    where id_furnizor = f_id_furnizor and
        lower(nume) = lower(f_nume) and 
        lower(culoare) = lower(f_culoare);
        
    return v_stoc;
    
exception
    when NO_DATA_FOUND then 
        return 0;
end;
/

CREATE OR REPLACE FUNCTION verifica_stoc_pentru_comanda
(
    p_id_buchet       IN componenta.ID_buchet%TYPE,
    p_numar_buchete   IN comanda.Numar_buchete%TYPE
)
RETURN NUMBER 
AS
    v_stoc_disponibil      floare.stoc%TYPE;
    v_total_flori_necesare NUMBER;
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM componenta
    WHERE id_buchet = p_id_buchet;
    
    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20032,
            'Nu exista buchetul cu id-ul ' || p_id_buchet
        );
    END IF;

    FOR rec IN (
        SELECT nume, culoare, cantitate
        FROM componenta
        WHERE ID_buchet = p_id_buchet
    ) LOOP
        v_stoc_disponibil := get_stoc_floare(rec.Nume, rec.Culoare);
        v_total_flori_necesare := rec.Cantitate * p_numar_buchete;

        IF v_stoc_disponibil < v_total_flori_necesare THEN
            dbms_output.put_line(
                'Stoc insuficient pentru ' || rec.nume ||
                ', culoare: ' || rec.culoare ||
                '. Cantitate necesara: ' || v_total_flori_necesare ||
                CHR(10) || 'Cantitate disponibila: ' || v_stoc_disponibil
            );

            RETURN 0;
        END IF;

    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Stoc suficient pentru comanda.');
    RETURN 1;
END verifica_stoc_pentru_comanda;
/

-- LARISA
CREATE OR REPLACE PROCEDURE creeaza_buchet
(
    p_ambalaj IN buchet.ambalaj%TYPE,
    p_pret_buchet IN buchet.pret%TYPE,
    p_componente IN pachet_buchete.t_lista_componente,

    p_id_buchet OUT buchet.id_buchet%TYPE
)
AS
BEGIN
    INSERT INTO buchet(ambalaj, pret)
    VALUES (p_ambalaj, p_pret_buchet)
    RETURNING ID_buchet INTO p_id_buchet;

    FOR i IN 1 .. p_componente.COUNT LOOP
        INSERT INTO componenta(ID_buchet, nume, culoare, cantitate)
        VALUES(p_id_buchet, p_componente(i).nume, p_componente(i).culoare, p_componente(i).cantitate);
    END LOOP;
END creeaza_buchet;
/

-- SIMONA
create or replace procedure decrementare_stoc_produs(
    p_id_furnizor produs.id_furnizor%type,
    p_nume produs.nume%type,
    p_culoare produs.culoare%type,
    p_cantitate produs.cantitate%type)as
begin

    update produs
    set cantitate = cantitate - p_cantitate
    where id_furnizor = p_id_furnizor and 
        lower(nume) = lower(p_nume) and 
        lower(culoare) = lower(p_culoare);
    
    if SQL%ROWCOUNT = 0 then
        RAISE_APPLICATION_ERROR(-20020, 'Produsul nu exista.');
    end if;
end;
/

CREATE TABLE Achizitie 
    ( 
     ID_achizitie   NUMBER (10)  NOT NULL , 
     ID_furnizor    NUMBER (10)  NOT NULL , 
     Data_achizitie DATE  NOT NULL , 
     Pret_total     NUMBER (8,2)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Achizitie 
    ADD CONSTRAINT achizitie_pret_ck 
    CHECK (pret_total >= 0) 
;

ALTER TABLE Achizitie 
    ADD CONSTRAINT Achizitie_PK PRIMARY KEY ( ID_achizitie ) ;

CREATE TABLE Produse_Achizitie 
    ( 
     ID_achizitie NUMBER (10)  NOT NULL , 
     ID_furnizor  NUMBER (10)  NOT NULL , 
     Nume         VARCHAR2 (20)  NOT NULL , 
     Culoare      VARCHAR2 (20)  NOT NULL , 
     Cantitate    NUMBER (3)  NOT NULL , 
     Pret         NUMBER (5,2)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Produse_Achizitie 
    ADD CONSTRAINT produse_achizitie_cantitate_ck 
    CHECK (cantitate > 0) 
;

ALTER TABLE Produse_Achizitie 
    ADD CONSTRAINT produs_achizitie_pret_ck 
    CHECK (pret > 0) 
;

-- SIMONA
create or replace procedure efectueaza_achizitie(
    p_id_furnizor produs.id_furnizor%type,
    p_lista_prod pachet_produse.prod_table_type)
as
    v_id_achizitie achizitie.id_achizitie%type;
    v_stoc produs.cantitate%type;
    v_pret produs.pret%type;
    v_pret_total achizitie.pret_total%type := 0;
begin
    insert into achizitie (id_furnizor, data_achizitie, pret_total)
        values (p_id_furnizor, sysdate, 0)
    returning id_achizitie into v_id_achizitie;
        
    for i in 1..p_lista_prod.count() loop
        v_stoc := get_stoc_produs(p_id_furnizor, p_lista_prod(i).nume, p_lista_prod(i).culoare);
        
        if v_stoc < p_lista_prod(i).cantitate then
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20324,
                'Stoc insuficient pentru produsul ' || p_lista_prod(i).nume);
        end if;
        
        decrementare_stoc_produs(p_id_furnizor, p_lista_prod(i).nume, p_lista_prod(i).culoare,
            p_lista_prod(i).cantitate);
        
        v_pret := get_pret_produs(p_id_furnizor, p_lista_prod(i).nume, p_lista_prod(i).culoare);
        insert into produse_achizitie(id_achizitie, id_furnizor, nume, culoare, cantitate, pret)
            values (v_id_achizitie, p_id_furnizor, p_lista_prod(i).nume, p_lista_prod(i).culoare, 
                p_lista_prod(i).cantitate, v_pret);
                
        v_pret_total := v_pret_total + p_lista_prod(i).cantitate * v_pret;
    end loop;
    
    
    update achizitie
        set pret_total = v_pret_total
    where id_achizitie = v_id_achizitie;
    
    COMMIT;
end;
/

-- LARISA
CREATE OR REPLACE PROCEDURE gaseste_buchet
(
    p_ambalaj IN buchet.ambalaj%TYPE,
    p_pret_buchet IN buchet.pret%TYPE,
    p_componente IN pachet_buchete.t_lista_componente,

    p_id_buchet OUT buchet.id_buchet%TYPE
)
AS
    v_nr_componente_buchet NUMBER;
    v_exista_componenta NUMBER;
    v_identic BOOLEAN;
BEGIN
    IF p_componente.COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20030, 'Buchetul trebuie sa aiba cel putin o componenta.');
    END IF;

    p_id_buchet := NULL;

    FOR b IN (
        SELECT ID_buchet
        FROM buchet
        WHERE ambalaj = p_ambalaj
            AND pret = p_pret_buchet
    ) LOOP
        SELECT COUNT(*)
        INTO v_nr_componente_buchet
        FROM componenta
        WHERE ID_buchet = b.ID_buchet;

        IF v_nr_componente_buchet = p_componente.COUNT THEN
            v_identic := TRUE;

            FOR i in 1 .. p_componente.COUNT LOOP
                SELECT COUNT(*)
                INTO v_exista_componenta
                FROM componenta
                WHERE ID_buchet = b.ID_buchet AND
                    nume = p_componente(i).nume AND
                    culoare = p_componente(i).culoare AND
                    cantitate = p_componente(i).cantitate;

                IF v_exista_componenta = 0 THEN
                    v_identic := FALSE;
                    EXIT;
                END IF;
            END LOOP;

            IF v_identic THEN
                p_id_buchet := b.ID_buchet;
                RETURN;
            END IF;
        END IF;
    END LOOP;
END gaseste_buchet;
/

CREATE TABLE Comanda 
    ( 
     ID_comanda    NUMBER (4)  NOT NULL , 
     ID_client     NUMBER (4)  NOT NULL , 
     ID_buchet     NUMBER (4)  NOT NULL , 
     Numar_buchete NUMBER (3)  NOT NULL , 
     Data_comenzii DATE  NOT NULL , 
     Pret          NUMBER (7,2)  NOT NULL , 
     Status        VARCHAR2 (30) 
    ) 
    LOGGING 
;

ALTER TABLE Comanda 
    ADD CONSTRAINT comanda_nr_buchete_ck 
    CHECK (numar_buchete > 0) 
;

ALTER TABLE Comanda 
    ADD CONSTRAINT comanda_pret_ck 
    CHECK (pret>0) 
;

ALTER TABLE Comanda 
    ADD CONSTRAINT comanda_status_ck 
    CHECK (Status IN ('Anulata', 'Finalizata', 'In pregatire', 'Livrata', 'Plasata')) 
;

ALTER TABLE Comanda 
    ADD CONSTRAINT Comanda_PK PRIMARY KEY ( ID_comanda ) ;

-- LARISA
CREATE OR REPLACE PROCEDURE plaseaza_comanda
(
    p_id_client IN client.id_client%TYPE,
    p_ambalaj IN buchet.ambalaj%TYPE,
    p_componente IN pachet_buchete.t_lista_componente,
    p_numar_buchete IN comanda.numar_buchete%TYPE,
    p_data_comenzii IN comanda.data_comenzii%TYPE
)
AS
    v_id_buchet buchet.id_buchet%TYPE;
    v_pret_buchet buchet.pret%TYPE;
BEGIN
    v_pret_buchet := calculeaza_pret_buchet(p_componente, p_ambalaj);

    -- verificare daca deja exista buchetul
    gaseste_buchet(p_ambalaj, v_pret_buchet, p_componente, v_id_buchet);

    -- daca buchetul nu exista deja, se creeaza
    IF v_id_buchet IS NULL THEN
        creeaza_buchet(p_ambalaj, v_pret_buchet, p_componente, v_id_buchet);
        DBMS_OUTPUT.PUT_LINE('S-a creat buchet nou cu ID-ul: ' || v_id_buchet);
    ELSE
        DBMS_OUTPUT.PUT_LINE('S-a gasit buchetul si are ID-ul: ' || v_id_buchet);
    END IF;

    -- verificare stoc
    IF verifica_stoc_pentru_comanda(v_id_buchet, p_numar_buchete) = 0 THEN
        ROLLBACK;

        RAISE_APPLICATION_ERROR(
            -20020,
            'Comanda nu a fost plasata din cauza stocului insuficient.'
        );
    END IF;

    -- stoc suficient, inserez comanda
    INSERT INTO comanda(ID_client, ID_buchet, numar_buchete, data_comenzii, pret, status)
    VALUES(p_id_client, v_id_buchet, p_numar_buchete, p_data_comenzii, v_pret_buchet * p_numar_buchete, 'Plasata');

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Comanda a fost plasata cu succes.');
END plaseaza_comanda;
/

CREATE TABLE Client 
    ( 
     ID_client NUMBER (4)  NOT NULL , 
     Nume      VARCHAR2 (20)  NOT NULL , 
     Prenume   VARCHAR2 (30)  NOT NULL , 
     Telefon   VARCHAR2 (10)  NOT NULL , 
     Email     VARCHAR2 (50) 
    ) 
    LOGGING 
;

ALTER TABLE Client 
    ADD CONSTRAINT client_nume_ck 
    CHECK (length(nume) > 1 AND regexp_like( nume, '^[a-zA-Z ]*$' )) 
;

ALTER TABLE Client 
    ADD CONSTRAINT client_prenume_ck 
    CHECK (length(prenume) > 1 AND regexp_like (prenume,  '^[a-zA-Z ]*$' )) 
;

ALTER TABLE Client 
    ADD CONSTRAINT client_telefon_ck 
    CHECK (length(telefon) = 10 AND regexp_like (telefon, '^[0][:7:3:2][0-9]*$')) 
;

ALTER TABLE Client 
    ADD CONSTRAINT client_email_ck 
    CHECK (regexp_like(email, '^[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}')) 
;

ALTER TABLE Client 
    ADD CONSTRAINT Client_PK PRIMARY KEY ( ID_client ) ;

ALTER TABLE Client 
    ADD CONSTRAINT Client_Telefon_UN UNIQUE ( Telefon ) ;

ALTER TABLE Client 
    ADD CONSTRAINT Client_Email_UN UNIQUE ( Email ) ;

CREATE TABLE Furnizor 
    ( 
     ID_furnizor NUMBER (10)  NOT NULL , 
     Nume        VARCHAR2 (30)  NOT NULL , 
     Telefon     VARCHAR2 (10)  NOT NULL , 
     Email       VARCHAR2 (50) 
    ) 
    LOGGING 
;

ALTER TABLE Furnizor 
    ADD CONSTRAINT furnizor_nume_ck 
    CHECK (length(nume) > 1 AND regexp_like(nume, '^[a-zA-Z ]*$')) 
;

ALTER TABLE Furnizor 
    ADD CONSTRAINT furnizor_telefon_ck 
    CHECK (length(telefon) = 10 AND regexp_like (telefon, '^[0][:7:3:2][0-9]*$')) 
;

ALTER TABLE Furnizor 
    ADD CONSTRAINT furnizor_email_ck 
    CHECK (regexp_like(email, '^[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}')) 
;

ALTER TABLE Furnizor 
    ADD CONSTRAINT Furnizor_PK PRIMARY KEY ( ID_furnizor ) ;

ALTER TABLE Furnizor 
    ADD CONSTRAINT Furnizor_Telefon_UN UNIQUE ( Telefon ) ;

ALTER TABLE Furnizor 
    ADD CONSTRAINT Furnizor_Email_UN UNIQUE ( Email ) ;

CREATE TABLE Tip_Floare 
    ( 
     Nume    VARCHAR2 (20)  NOT NULL , 
     Culoare VARCHAR2 (20)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Tip_Floare 
    ADD CONSTRAINT Tip_Floare_PK PRIMARY KEY ( Nume, Culoare ) ;

ALTER TABLE Achizitie 
    ADD CONSTRAINT Achizitie_Furnizor_FK FOREIGN KEY 
    ( 
     ID_furnizor
    ) 
    REFERENCES Furnizor 
    ( 
     ID_furnizor
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Comanda 
    ADD CONSTRAINT Comanda_Buchet_FK FOREIGN KEY 
    ( 
     ID_buchet
    ) 
    REFERENCES Buchet 
    ( 
     ID_buchet
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Comanda 
    ADD CONSTRAINT Comanda_Client_FK FOREIGN KEY 
    ( 
     ID_client
    ) 
    REFERENCES Client 
    ( 
     ID_client
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Componenta 
    ADD CONSTRAINT Componenta_Buchet_FK FOREIGN KEY 
    ( 
     ID_buchet
    ) 
    REFERENCES Buchet 
    ( 
     ID_buchet
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Componenta 
    ADD CONSTRAINT Componenta_Floare_FK FOREIGN KEY 
    ( 
     Culoare,
     Nume
    ) 
    REFERENCES Floare 
    ( 
     Culoare,
     Nume
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Floare 
    ADD CONSTRAINT Floare_Tip_Floare_FK FOREIGN KEY 
    ( 
     Nume,
     Culoare
    ) 
    REFERENCES Tip_Floare 
    ( 
     Nume,
     Culoare
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Produs 
    ADD CONSTRAINT Produs_Furnizor_FK FOREIGN KEY 
    ( 
     ID_furnizor
    ) 
    REFERENCES Furnizor 
    ( 
     ID_furnizor
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Produs 
    ADD CONSTRAINT Produs_Tip_Floare_FK FOREIGN KEY 
    ( 
     Nume,
     Culoare
    ) 
    REFERENCES Tip_Floare 
    ( 
     Nume,
     Culoare
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Produse_Achizitie 
    ADD CONSTRAINT Produse_Achizitie_Achizitie_FK FOREIGN KEY 
    ( 
     ID_achizitie
    ) 
    REFERENCES Achizitie 
    ( 
     ID_achizitie
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Produse_Achizitie 
    ADD CONSTRAINT Produse_Achizitie_Produs_FK FOREIGN KEY 
    ( 
     ID_furnizor,
     Culoare,
     Nume
    ) 
    REFERENCES Produs 
    ( 
     ID_furnizor,
     Culoare,
     Nume
    ) 
    NOT DEFERRABLE 
;

CREATE OR REPLACE TRIGGER trg_achizitie_data 
    BEFORE INSERT OR UPDATE ON Achizitie 
    FOR EACH ROW 
BEGIN
	IF( :new.data_achizitie > SYSDATE )
	THEN 
		RAISE_APPLICATION_ERROR( -20001,
			'Data invalida: ' || TO_CHAR( :new.data_achizitie, 'DD.MM.YYYY HH24:MI:SS' ) || ' este in viitor.' );
	END IF;
END; 
/

CREATE OR REPLACE TRIGGER trg_actualizare_stoc_dupa_comanda 
    AFTER INSERT ON Comanda 
    FOR EACH ROW 
BEGIN
--LARISA
    FOR rec IN (
        SELECT nume, culoare, cantitate
        FROM componenta c
        WHERE c.ID_buchet = :NEW.ID_buchet
    ) LOOP
        UPDATE floare
        SET stoc = stoc - (rec.cantitate * :NEW.numar_buchete)
        WHERE nume = rec.nume AND
            culoare = rec.culoare;
    END LOOP;
END; 
/

CREATE OR REPLACE TRIGGER trg_anulare_comanda 
    AFTER UPDATE OF Status ON Comanda 
    FOR EACH ROW 
    WHEN ( NEW.status = 'Anulata' and OLD.status != 'Anulata' ) 
declare
    cursor c_componenta is
        select nume, culoare, cantitate
        from componenta
        where id_buchet = :OLD.id_buchet;
begin
-- SIMONA
    if :OLD.status = 'Plasata' then
        for c in c_componenta loop
            update floare
                set stoc = stoc + :OLD.numar_buchete * c.cantitate
                where lower(nume) = lower(c.nume) and 
                    lower(culoare) = lower(c.culoare);
            
            if SQL%ROWCOUNT = 0 then
                ROLLBACK;
                RAISE_APPLICATION_ERROR(-20020, 'Floarea ' || c.nume || 
                    ' ' || c.culoare || ' nu exista.');
            end if;
        end loop;
    end if;
end; 
/

CREATE OR REPLACE TRIGGER trg_comanda_data 
    BEFORE INSERT OR UPDATE ON Comanda 
    FOR EACH ROW 
BEGIN
	IF( :new.data_comenzii <= SYSDATE )
	THEN 
		RAISE_APPLICATION_ERROR( -20001,
			'Data invalida: ' || TO_CHAR( :new.data_comenzii, 'DD.MM.YYYY HH24:MI:SS' ) || ' trebuie sa fie mai mare decat data curenta.' );
	END IF;
END; 
/

CREATE OR REPLACE TRIGGER trg_update_pret_buchet 
    AFTER UPDATE OF Pret ON Floare 
    FOR EACH ROW 
BEGIN
-- LARISA
    FOR rec IN (
        SELECT ID_buchet, cantitate
        FROM componenta
        WHERE nume = :NEW.nume AND
            culoare = :NEW.culoare
    ) LOOP
        UPDATE buchet
        SET pret = pret + ((:NEW.pret - :OLD.pret) * rec.cantitate)
        WHERE ID_buchet = rec.ID_buchet;
    END LOOP;
END; 
/

CREATE OR REPLACE TRIGGER trg_update_stoc_la_achizitie 
    AFTER INSERT ON Produse_Achizitie 
    FOR EACH ROW 
declare
    v_count number;
begin
-- SIMONA
    select count(*) into v_count
    from floare
    where lower(nume) = lower(:NEW.nume) and
        lower(culoare) = lower(:NEW.culoare);
        
    if v_count > 0 then
        update floare
        SET stoc = stoc + :NEW.cantitate
        where lower(nume) = lower(:NEW.nume) and
            lower(culoare) = lower(:NEW.culoare);
    else
        -- daca nu exista in florarie, adaugam
        insert into floare (nume, culoare, pret, stoc) values
            (:NEW.nume, :NEW.culoare, :NEW.pret * 1.5, :NEW.cantitate);
    end if;
    
end; 
/

CREATE SEQUENCE Achizitie_ID_achizitie_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Achizitie_ID_achizitie_TRG 
BEFORE INSERT ON Achizitie 
FOR EACH ROW 
WHEN (NEW.ID_achizitie IS NULL) 
BEGIN 
    :NEW.ID_achizitie := Achizitie_ID_achizitie_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Buchet_ID_buchet_SEQ 
START WITH 500 
    MINVALUE 500 
    MAXVALUE 1000 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Buchet_ID_buchet_TRG 
BEFORE INSERT ON Buchet 
FOR EACH ROW 
WHEN (NEW.ID_buchet IS NULL) 
BEGIN 
    :NEW.ID_buchet := Buchet_ID_buchet_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Client_ID_client_SEQ 
START WITH 2000 
    MINVALUE 2000 
    MAXVALUE 3000 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Client_ID_client_TRG 
BEFORE INSERT ON Client 
FOR EACH ROW 
WHEN (NEW.ID_client IS NULL) 
BEGIN 
    :NEW.ID_client := Client_ID_client_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Comanda_ID_comanda_SEQ 
START WITH 1000 
    MINVALUE 1000 
    MAXVALUE 2000 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Comanda_ID_comanda_TRG 
BEFORE INSERT ON Comanda 
FOR EACH ROW 
WHEN (NEW.ID_comanda IS NULL) 
BEGIN 
    :NEW.ID_comanda := Comanda_ID_comanda_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Furnizor_ID_furnizor_SEQ 
START WITH 5000 
    MINVALUE 5000 
    MAXVALUE 6000 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Furnizor_ID_furnizor_TRG 
BEFORE INSERT ON Furnizor 
FOR EACH ROW 
WHEN (NEW.ID_furnizor IS NULL) 
BEGIN 
    :NEW.ID_furnizor := Furnizor_ID_furnizor_SEQ.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             43
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           2
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         5
-- CREATE FUNCTION                          5
-- CREATE TRIGGER                          11
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          5
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
